micronaut:
  server:
    port: 7002
datasources:
  default:
    url: jdbc:mysql://localhost/microservices-study
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: password
    schema-generate: CREATE_DROP
    dialect: MYSQL
